# Agenda

1. NumPy
2. Pandas series
3. Data frames
4. Indexes, sorting, grouping
5. Dates + times
6. Optimization of time + memory + speed

In [1]:
x = 5



In [2]:
type(x)

int

In [3]:
x = 'abcd'
type(x)

str

In [4]:
x = 0

import sys
sys.getsizeof(x)

28

In [5]:
x = 100000

In [6]:
sys.getsizeof(x)

28

In [7]:
x = x ** 1000

In [8]:
sys.getsizeof(x)

2240

# NumPy 

C data with a Python API

In [9]:
import numpy as np

In [10]:
# NumPy nd-array 

np.ndarray

numpy.ndarray

In [11]:
# create a NumPy array
a = np.array([10,20, 30, 40, 50, 60])
a

array([10, 20, 30, 40, 50, 60])

In [12]:
type(a)

numpy.ndarray

In [13]:
# standard Python operations

a[0]

np.int64(10)

In [14]:
a[1:4]

array([20, 30, 40])

In [15]:
a[1:4][0]

np.int64(20)

In [16]:
np.__version__

'2.2.2'

In [17]:
a[0]

np.int64(10)

In [18]:
a.sum()

np.int64(210)

In [19]:
a.mean()

np.float64(35.0)

In [20]:
a.std()

np.float64(17.07825127659933)

In [21]:
a.min()

np.int64(10)

In [22]:
a.max()

np.int64(60)

In [23]:
mylist1 = [10, 20, 30]
mylist2 = [40, 50, 60]

mylist1 + mylist2

[10, 20, 30, 40, 50, 60]

In [24]:
a

array([10, 20, 30, 40, 50, 60])

In [25]:
a + a

array([ 20,  40,  60,  80, 100, 120])

In [26]:
a / a

array([1., 1., 1., 1., 1., 1.])

In [27]:
a * a

array([ 100,  400,  900, 1600, 2500, 3600])

In [28]:
mylist1 + 5

TypeError: can only concatenate list (not "int") to list

In [29]:
# broadcast
a + 5

array([15, 25, 35, 45, 55, 65])

# Operations on NumPy arrays

- If we run an operator on two arrays, we get a new array back with the operation applied to each index
- If we run an operation on an array and a scalar value, we get a new array back -- the operation broadcast to each index

In [30]:
a

array([10, 20, 30, 40, 50, 60])

In [31]:
a[2] = 999
a

array([ 10,  20, 999,  40,  50,  60])

# Other ways to create a NumPy array

1. `np.arange`
2. `np.random.randint`
3. `np.random.rand`

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [40]:
np.random.seed(0)   # dictate the random number generator start
np.random.randint(0, 100, 5)

array([44, 47, 64, 67, 67])

In [41]:
np.random.seed(0)
np.random.rand(10)   # 10 floats from 0 to 1


array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [44]:
np.random.seed(0)
np.random.rand(10)  * 100

array([54.88135039, 71.51893664, 60.27633761, 54.4883183 , 42.36547993,
       64.58941131, 43.75872113, 89.17730008, 96.36627605, 38.34415188])