# Agenda

1. NumPy
2. Pandas series
3. Data frames
4. Indexes, sorting, grouping
5. Dates + times
6. Optimization of time + memory + speed

In [1]:
x = 5



In [2]:
type(x)

int

In [3]:
x = 'abcd'
type(x)

str

In [4]:
x = 0

import sys
sys.getsizeof(x)

28

In [5]:
x = 100000

In [6]:
sys.getsizeof(x)

28

In [7]:
x = x ** 1000

In [8]:
sys.getsizeof(x)

2240

# NumPy 

C data with a Python API

In [9]:
import numpy as np

In [10]:
# NumPy nd-array 

np.ndarray

numpy.ndarray

In [11]:
# create a NumPy array
a = np.array([10,20, 30, 40, 50, 60])
a

array([10, 20, 30, 40, 50, 60])

In [12]:
type(a)

numpy.ndarray

In [13]:
# standard Python operations

a[0]

np.int64(10)

In [14]:
a[1:4]

array([20, 30, 40])

In [15]:
a[1:4][0]

np.int64(20)

In [16]:
np.__version__

'2.2.2'

In [17]:
a[0]

np.int64(10)

In [18]:
a.sum()

np.int64(210)

In [19]:
a.mean()

np.float64(35.0)

In [20]:
a.std()

np.float64(17.07825127659933)

In [21]:
a.min()

np.int64(10)

In [22]:
a.max()

np.int64(60)

In [23]:
mylist1 = [10, 20, 30]
mylist2 = [40, 50, 60]

mylist1 + mylist2

[10, 20, 30, 40, 50, 60]

In [24]:
a

array([10, 20, 30, 40, 50, 60])

In [25]:
a + a

array([ 20,  40,  60,  80, 100, 120])

In [26]:
a / a

array([1., 1., 1., 1., 1., 1.])

In [27]:
a * a

array([ 100,  400,  900, 1600, 2500, 3600])

In [28]:
mylist1 + 5

TypeError: can only concatenate list (not "int") to list

In [29]:
# broadcast
a + 5

array([15, 25, 35, 45, 55, 65])

# Operations on NumPy arrays

- If we run an operator on two arrays, we get a new array back with the operation applied to each index
- If we run an operation on an array and a scalar value, we get a new array back -- the operation broadcast to each index

In [30]:
a

array([10, 20, 30, 40, 50, 60])

In [31]:
a[2] = 999
a

array([ 10,  20, 999,  40,  50,  60])

# Other ways to create a NumPy array

1. `np.arange`
2. `np.random.randint`
3. `np.random.rand`
4. `np.ones`
5. `np.zeros`

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [40]:
np.random.seed(0)   # dictate the random number generator start
np.random.randint(0, 100, 5)

array([44, 47, 64, 67, 67])

In [41]:
np.random.seed(0)
np.random.rand(10)   # 10 floats from 0 to 1


array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [44]:
np.random.seed(0)
np.random.rand(10)  * 100

array([54.88135039, 71.51893664, 60.27633761, 54.4883183 , 42.36547993,
       64.58941131, 43.75872113, 89.17730008, 96.36627605, 38.34415188])

In [45]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [46]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

# Exercises: NumPy arrays

- https://github.com/reuven   
- repositories 
- apple-2025-02February-pandas
- Jupyter notebook there

1. Create a 3-element NumPy array with your birthday (year, month, day)
2. Change the year to be this year.
3. Create an array with 10 random ints from 0-100.
4. Find the mean and std of these numbers.
5. Create an array of 10 random floats from 0-1,000.
6. Find the mean and std of these numbers.

In [47]:
a = np.array([1970, 7, 14])
a

array([1970,    7,   14])

In [48]:
a = np.array([123456789,1,2])

In [49]:
a

array([123456789,         1,         2])

In [50]:
a = np.array([1970, 7, 14])
a

array([1970,    7,   14])

In [51]:
a[0] = 2025
a

array([2025,    7,   14])

In [53]:
# 3. Create an array with 10 random ints from 0-100.

np.random.seed(0)
a = np.random.randint(0, 100, 10)
a

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

In [54]:
# 4. Find the mean and std of these numbers.
a.mean()

np.float64(52.5)

In [55]:
a.std()

np.float64(24.3567239176372)

In [56]:
# 5. Create an array of 10 random floats from 0-1,000.

np.random.seed(0)
a = np.random.rand(10) * 1000
a

array([548.81350393, 715.18936637, 602.76337607, 544.883183  ,
       423.65479934, 645.89411307, 437.58721126, 891.77300078,
       963.6627605 , 383.44151883])

In [57]:
# 6. Find the mean and std of these numbers.

a.mean()

np.float64(615.7662833145425)

In [58]:
a.std()

np.float64(184.47489445957166)

In [59]:
np.random.seed(0)
a = np.random.randint(0, 100, 10)
a

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

In [60]:
# get from index 3
a[3]

np.int64(67)

In [61]:
# get from index 5
a[5]

np.int64(9)

In [65]:
# what if I want from both 3 and 5?
# fancy indexing!

a[ [3, 5] ]

array([67,  9])

In [63]:
a[ [5, 3]]

array([ 9, 67])

In [64]:
a[[3,5,3,5]]

array([67,  9, 67,  9])

In [66]:
a

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

In [67]:
# broadcast

a * 4

array([176, 188, 256, 268, 268,  36, 332,  84, 144, 348])

In [68]:
a < 50

array([ True,  True, False, False, False,  True, False,  True,  True,
       False])

In [69]:
a < a.mean()

array([ True,  True, False, False, False,  True, False,  True,  True,
       False])

In [70]:
# mask index

# get back the values of a that correspond to True
a[ [True, True, True, True, False, False, False, False, True, True]  ]

array([44, 47, 64, 67, 36, 87])

In [72]:
# get the elements of a that are < 50
a[ a < 50 ]

array([44, 47,  9, 21, 36])

In [73]:
a[ a < a.mean() ]

array([44, 47,  9, 21, 36])

# Exercise: Boolean indexes

1. Create a NumPy array with 20 random ints from 0-100.
2. Find the smallest number that is bigger than 50.
3. Find the largest number that is less than the mean - 1 std.
4. Find the mean of the numbers that are less than the mean.

In [74]:
np.random.seed(0)
a = np.random.randint(0, 100, 20)
a

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87, 46, 88])

In [77]:
# 2. Find the smallest number that is bigger than 50.

a[a > 50].min()

np.int64(58)

In [85]:
# 3. Find the largest number that is less than the mean - 1 std.

a[a < (a.mean() - a.std())].max()

np.int64(21)

In [84]:
# 4. Find the mean of the numbers that are less than the mean.

a[a < a.mean()].mean()

np.float64(34.666666666666664)

In [88]:
# what if I want all of the even numbers?

a[a % 2 == 0]

array([44, 64, 36, 70, 88, 88, 12, 58, 46, 88])

In [87]:
a

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87, 46, 88])

In [90]:
a = np.array([10, 25, 30])

a[[True, False, True]]

array([10, 30])

In [91]:
a % 2

array([0, 1, 0])

In [92]:
a[a%2]   # just like saying a[[0, 1, 0]]  -- not a[[False, True, False]]

array([10, 25, 10])

In [93]:
a[a%2 ==1]

array([25])

In [94]:
# find even numbers that are less than the mean

np.random.seed(0)
a = np.random.randint(0, 1000, 20)
a

array([684, 559, 629, 192, 835, 763, 707, 359,   9, 723, 277, 754, 804,
       599,  70, 472, 600, 396, 314, 705])

In [95]:
a[a%2 == 0    and a < a.mean()]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [96]:
x = 0

if x:
    print('It is True-ish')
else:
    print('It is False-ish')

It is False-ish


# NumPy uses binary operators

- `|` -- "or" for NumPy expressions
- `&` -- "and" for NumPy expressions
- `~` -- "not" for NumPy expressions

In [101]:
(a%2 == 0)  * (a < a.mean())

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True,  True, False,  True,
        True, False])

In [102]:
a[(a%2 == 0)  &  (a < a.mean())]

array([192,  70, 472, 396, 314])

In [104]:
# return numbers that are either even *or* less than the mean
a[(a%2 == 0) |  (a < a.mean())]

array([684, 192, 359,   9, 277, 754, 804,  70, 472, 600, 396, 314])

In [106]:
# even *xor* less than the mean (but not both)
a[(a%2 == 0) ^  (a < a.mean())]

array([684, 359,   9, 277, 754, 804, 600])

In [107]:
a[(a%2 == 0) |
 (a < a.mean())]

array([684, 192, 359,   9, 277, 754, 804,  70, 472, 600, 396, 314])

In [108]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [109]:
a[0]

np.int64(10)

In [110]:
# dtype -- 

a.dtype

dtype('int64')

In [111]:
# if I create an array, NumPy:
# - int64
# - float64
# - string (we won't deal with this)

a = np.array([10, 20, 30, 40, 50])
a.dtype

dtype('int64')

In [114]:
a = np.array([10, 20, 30, 40, 50], dtype=np.int32)
a

array([10, 20, 30, 40, 50], dtype=int32)

In [115]:
a = np.array([10, 20, 30, 40, 50], dtype='int32')
a

array([10, 20, 30, 40, 50], dtype=int32)

# What dtypes do we have?

- int
    - `int64`
    - `int32`
    - `int16`
    - `int8`
- unsigned int
    - `uint64`
    - `uint32`
    - `uint16`
    - `uint8`
- float
    - `float64`
    - `float32`


In [116]:
a = np.array([10, 20, 30, 40, 50], dtype='int8')
a

array([10, 20, 30, 40, 50], dtype=int8)

In [117]:
a * 100

array([ -24,  -48,  -72,  -96, -120], dtype=int8)

In [118]:
a * 1000

OverflowError: Python integer 1000 out of bounds for int8

In [119]:
a = np.array([10, 20, 30, 40, 50], dtype='uint8')
a

array([10, 20, 30, 40, 50], dtype=uint8)

In [120]:
a * 100

array([232, 208, 184, 160, 136], dtype=uint8)

In [121]:
a


array([10, 20, 30, 40, 50], dtype=uint8)

In [122]:
a[2] = 123.456

In [123]:
a

array([ 10,  20, 123,  40,  50], dtype=uint8)

In [124]:
a[3] = '98'

In [125]:
a

array([ 10,  20, 123,  98,  50], dtype=uint8)

In [126]:
a[3] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

In [127]:
a

array([ 10,  20, 123,  98,  50], dtype=uint8)

In [128]:
a.dtype  = np.uint16

ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.

In [129]:
a = np.array([10, 20, 30, 40, 50], dtype='uint64')


In [130]:
a.dtype = np.uint32

In [131]:
a

array([10,  0, 20,  0, 30,  0, 40,  0, 50,  0], dtype=uint32)

In [132]:
a.dtype = np.uint16
a

array([10,  0,  0,  0, 20,  0,  0,  0, 30,  0,  0,  0, 40,  0,  0,  0, 50,
        0,  0,  0], dtype=uint16)

In [133]:
a.dtype = np.float64

In [134]:
a

array([4.94e-323, 9.88e-323, 1.48e-322, 1.98e-322, 2.47e-322])

In [135]:
a.dtype = np.uint64
a

array([10, 20, 30, 40, 50], dtype=uint64)

In [136]:
# astype

a.astype('float64')

array([10., 20., 30., 40., 50.])

In [137]:
a = np.array([10, 20, 30.5, 40, 50])
a

array([10. , 20. , 30.5, 40. , 50. ])

In [138]:
a.dtype

dtype('float64')

In [139]:
a.astype('int64')

array([10, 20, 30, 40, 50])

In [140]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=np.float16)

In [141]:
a

array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=float16)

In [142]:
a + 0.1

array([0.2   , 0.2998, 0.4   , 0.5   , 0.6   ], dtype=float16)

In [143]:
0.1 + 0.2

0.30000000000000004

In [145]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=np.float64)
a + 0.1

array([0.2, 0.3, 0.4, 0.5, 0.6])

In [146]:
a = np.array('this is a great example'.split())
a

array(['this', 'is', 'a', 'great', 'example'], dtype='<U7')

In [147]:
a[0] = 'abcdefghij'
a

array(['abcdefg', 'is', 'a', 'great', 'example'], dtype='<U7')

# Exercise: dtypes

1. Define a NumPy array with 20 floats from 0-1,000.
2. Calculate the mean of all numbers whose int portion is even.

In [148]:
np.random.seed(0)

a = np.random.rand(20) * 1000
a

array([548.81350393, 715.18936637, 602.76337607, 544.883183  ,
       423.65479934, 645.89411307, 437.58721126, 891.77300078,
       963.6627605 , 383.44151883, 791.72503808, 528.89491975,
       568.04456109, 925.59663829,  71.0360582 ,  87.1292997 ,
        20.21839744, 832.61984555, 778.15675095, 870.01214825])

In [154]:
a[a.astype('int64') % 2 == 0].mean()

np.float64(588.2674095586261)

In [155]:
a = np.array([10, 20, 30, 40, 50])

a[[2, 4]]

array([30, 50])

In [156]:
a[[2, 4]] = 99
a

array([10, 20, 99, 40, 99])

In [158]:
a = np.array([10, 20, 30, 40, 50])

a[a < a.mean()] = 99
a

array([99, 99, 30, 40, 50])

In [159]:
a = np.array([  95, 90, 97, 80, 0  ])

a.mean()

np.float64(72.4)

# `nan` -- not a number



In [160]:
np.nan

nan

In [161]:
np.NaN

AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

In [162]:
type(np.nan)

float

In [163]:
np.nan > 0

False

In [164]:
np.nan == 0

False

In [165]:
np.nan < 0

False

In [166]:
np.nan == np.nan

False

In [167]:
a = np.array([10, 20, 30, np.nan, 40, 50])
a

array([10., 20., 30., nan, 40., 50.])

In [168]:
a.mean()

np.float64(nan)

In [169]:
a.sum()

np.float64(nan)

In [170]:
a.min()

np.float64(nan)

In [171]:
a.max()

np.float64(nan)

In [172]:
a[ a != np.nan ]

array([10., 20., 30., nan, 40., 50.])

In [173]:
np.isnan(a)

array([False, False, False,  True, False, False])

In [174]:
a[np.isnan(a)]

array([nan])

In [175]:
a[~np.isnan(a)]

array([10., 20., 30., 40., 50.])

In [176]:
a[~np.isnan(a)].mean()

np.float64(30.0)

In [179]:
~(np.array([10, 20, 30, 40]))

array([-11, -21, -31, -41])

In [180]:
a = np.array([10, 20, 30 ,40, 50])
a[2] = np.nan

ValueError: cannot convert float NaN to integer

In [182]:
a = np.array([10, 20, 30 ,40, 50], dtype=np.float16)
a[2] = np.nan
a

array([10., 20., nan, 40., 50.], dtype=float16)

# Execise: nan and replacement

1. Create an array of 20 floats from 0-1,000.
2. Replace all numbers whose integer part is even to `np.nan`.
3. Calculate the mean of all remaining numbers.
4. Replace all of the `np.nan` values with that mean (from step 3)

In [183]:
np.random.seed(0)
a = np.random.rand(20) * 1000
a

array([548.81350393, 715.18936637, 602.76337607, 544.883183  ,
       423.65479934, 645.89411307, 437.58721126, 891.77300078,
       963.6627605 , 383.44151883, 791.72503808, 528.89491975,
       568.04456109, 925.59663829,  71.0360582 ,  87.1292997 ,
        20.21839744, 832.61984555, 778.15675095, 870.01214825])

In [186]:
a[a.astype('int64') % 2 == 0] = np.nan

In [187]:
a

array([         nan, 715.18936637,          nan,          nan,
       423.65479934, 645.89411307, 437.58721126, 891.77300078,
       963.6627605 , 383.44151883, 791.72503808,          nan,
                nan, 925.59663829,  71.0360582 ,  87.1292997 ,
                nan,          nan,          nan,          nan])

In [188]:
a.mean()

np.float64(nan)

In [193]:
a[np.isnan(a)] = a[~np.isnan(a)].mean()

In [194]:
a

array([576.06270949, 715.18936637, 576.06270949, 576.06270949,
       423.65479934, 645.89411307, 437.58721126, 891.77300078,
       963.6627605 , 383.44151883, 791.72503808, 576.06270949,
       576.06270949, 925.59663829,  71.0360582 ,  87.1292997 ,
       576.06270949, 576.06270949, 576.06270949, 576.06270949])

In [195]:
a.mean()

np.float64(576.0627094931192)

In [196]:
np.random.seed(0)
a = np.random.randint(-50, 50, 10)
a

array([ -6,  -3,  14,  17,  17, -41,  33, -29, -14,  37])

In [197]:
a.sort()

In [198]:
a

array([-41, -29, -14,  -6,  -3,  14,  17,  17,  33,  37])

In [199]:
help(a.sort)

Help on built-in function sort:

sort(...) method of numpy.ndarray instance
    a.sort(axis=-1, kind=None, order=None)

    Sort an array in-place. Refer to `numpy.sort` for full documentation.

    Parameters
    ----------
    axis : int, optional
        Axis along which to sort. Default is -1, which means sort along the
        last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort under the covers and, in general, the
        actual implementation will vary with datatype. The 'mergesort' option
        is retained for backwards compatibility.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields will still be u

In [200]:
# 2D arrays

a = np.array([[10, 20, 30],
             [40, 50, 60],
             [70, 80, 90],
             [100, 110, 120]])

In [201]:
type(a)

numpy.ndarray

In [202]:
a.size

12

In [203]:
a.shape

(4, 3)

In [204]:
a.sum()

np.int64(780)

In [205]:
a.mean()

np.float64(65.0)

In [206]:
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [207]:
# get a row

a[1]

array([40, 50, 60])

In [208]:
a[3]

array([100, 110, 120])

In [209]:
# row index 1, column index 1

a[1][1]  # unfortunately, this works!

np.int64(50)

In [210]:
a[1, 1]

np.int64(50)

In [211]:
# rows 1 + 3, column 1
a[ [1, 3],   1]

array([ 50, 110])

In [212]:
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [213]:
# get all columns
a[ [1, 3],   :]

array([[ 40,  50,  60],
       [100, 110, 120]])

In [214]:
# just column index 1

a[:, 1]

array([ 20,  50,  80, 110])

In [216]:
# rows 1+3
# columns 1+2

# no! he'll give [1,3 ] and [1,2]
a[ [1,3], [1, 2] ]

array([ 50, 120])

In [217]:
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [218]:
a.shape 

(4, 3)

In [219]:
a.reshape(6,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100],
       [110, 120]])

In [220]:
b = a.reshape(6, 2)
b

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100],
       [110, 120]])

In [221]:
b[1, 1] = 999
b

array([[ 10,  20],
       [ 30, 999],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100],
       [110, 120]])

In [222]:
a

array([[ 10,  20,  30],
       [999,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [223]:
np.shares_memory(a, b)

True

In [224]:
a

array([[ 10,  20,  30],
       [999,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [225]:
a.sum()

np.int64(1739)

In [226]:
a.sum(axis=0)

array([1179,  260,  300])

In [227]:
a.sum(axis=1)

array([  60, 1109,  240,  330])

In [228]:
a.sort(axis=0)
a

array([[ 10,  20,  30],
       [ 70,  50,  60],
       [100,  80,  90],
       [999, 110, 120]])

In [229]:
a

array([[ 10,  20,  30],
       [ 70,  50,  60],
       [100,  80,  90],
       [999, 110, 120]])

In [230]:
a.shape = (2, 6)

In [231]:
a

array([[ 10,  20,  30,  70,  50,  60],
       [100,  80,  90, 999, 110, 120]])

In [ ]:
a.reshape()